spring:
  application.name: secom-mms-gateway
  datasource:
    url: jdbc:postgresql://localhost/test
    username: test
    password: test
  flyway:
    baseline-on-migrate: true

secom:
  security:
    ssl:
      keystore: /home/oliver/IdeaProjects/secom-mms-gateway/src/main/resources/keystore.p12
      keystorePassword: changeit
      insecureSslPolicy: true

international:
  dmc:
    secom_mms_gateway:
      keystore:
        path: ${secom.security.ssl.keystore}
        password: ${secom.security.ssl.keystorePassword}
        alias: 1
      rootCA:
        path:
      secom:
        dataProductType: S124
      mms:
        mms-edgerouter:
          url: wss://eu-edgerouter.dmc.international:8888/
        own-mrn: urn:mrn:mcp:service:mcc:core:secom-mms-gateway
