// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmtp.proto

// Protobuf Java Version: 3.25.2
package mmtp;

public interface DisconnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Disconnect)
    com.google.protobuf.MessageOrBuilder {
}
