// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmtp.proto

// Protobuf Java Version: 3.25.2
package mmtp;

public interface FilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Filter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string messageUuids = 1;</code>
   * @return A list containing the messageUuids.
   */
  java.util.List<String>
      getMessageUuidsList();
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @return The count of messageUuids.
   */
  int getMessageUuidsCount();
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @param index The index of the element to return.
   * @return The messageUuids at the given index.
   */
  String getMessageUuids(int index);
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the messageUuids at the given index.
   */
  com.google.protobuf.ByteString
      getMessageUuidsBytes(int index);
}
