// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmtp.proto

// Protobuf Java Version: 3.25.2
package mmtp;

/**
 * Protobuf type {@code Filter}
 */
public final class Filter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Filter)
    FilterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Filter.newBuilder() to construct.
  private Filter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Filter() {
    messageUuids_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Filter();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Filter_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Filter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.Filter.class, net.maritimeconnectivity.mmtp.Filter.Builder.class);
  }

  public static final int MESSAGEUUIDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList messageUuids_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @return A list containing the messageUuids.
   */
  public com.google.protobuf.ProtocolStringList
      getMessageUuidsList() {
    return messageUuids_;
  }
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @return The count of messageUuids.
   */
  public int getMessageUuidsCount() {
    return messageUuids_.size();
  }
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @param index The index of the element to return.
   * @return The messageUuids at the given index.
   */
  public String getMessageUuids(int index) {
    return messageUuids_.get(index);
  }
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the messageUuids at the given index.
   */
  public com.google.protobuf.ByteString
      getMessageUuidsBytes(int index) {
    return messageUuids_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < messageUuids_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageUuids_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < messageUuids_.size(); i++) {
        dataSize += computeStringSizeNoTag(messageUuids_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMessageUuidsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.Filter)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.Filter other = (net.maritimeconnectivity.mmtp.Filter) obj;

    if (!getMessageUuidsList()
        .equals(other.getMessageUuidsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMessageUuidsCount() > 0) {
      hash = (37 * hash) + MESSAGEUUIDS_FIELD_NUMBER;
      hash = (53 * hash) + getMessageUuidsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.Filter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Filter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Filter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Filter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Filter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Filter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Filter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Filter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.Filter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.Filter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Filter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Filter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.Filter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Filter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Filter)
      net.maritimeconnectivity.mmtp.FilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Filter_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Filter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.Filter.class, net.maritimeconnectivity.mmtp.Filter.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.Filter.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageUuids_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Filter_descriptor;
    }

    @Override
    public net.maritimeconnectivity.mmtp.Filter getDefaultInstanceForType() {
      return net.maritimeconnectivity.mmtp.Filter.getDefaultInstance();
    }

    @Override
    public net.maritimeconnectivity.mmtp.Filter build() {
      net.maritimeconnectivity.mmtp.Filter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public net.maritimeconnectivity.mmtp.Filter buildPartial() {
      net.maritimeconnectivity.mmtp.Filter result = new net.maritimeconnectivity.mmtp.Filter(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.Filter result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        messageUuids_.makeImmutable();
        result.messageUuids_ = messageUuids_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.Filter) {
        return mergeFrom((net.maritimeconnectivity.mmtp.Filter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.Filter other) {
      if (other == net.maritimeconnectivity.mmtp.Filter.getDefaultInstance()) return this;
      if (!other.messageUuids_.isEmpty()) {
        if (messageUuids_.isEmpty()) {
          messageUuids_ = other.messageUuids_;
          bitField0_ |= 0x00000001;
        } else {
          ensureMessageUuidsIsMutable();
          messageUuids_.addAll(other.messageUuids_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              ensureMessageUuidsIsMutable();
              messageUuids_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList messageUuids_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureMessageUuidsIsMutable() {
      if (!messageUuids_.isModifiable()) {
        messageUuids_ = new com.google.protobuf.LazyStringArrayList(messageUuids_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string messageUuids = 1;</code>
     * @return A list containing the messageUuids.
     */
    public com.google.protobuf.ProtocolStringList
        getMessageUuidsList() {
      messageUuids_.makeImmutable();
      return messageUuids_;
    }
    /**
     * <code>repeated string messageUuids = 1;</code>
     * @return The count of messageUuids.
     */
    public int getMessageUuidsCount() {
      return messageUuids_.size();
    }
    /**
     * <code>repeated string messageUuids = 1;</code>
     * @param index The index of the element to return.
     * @return The messageUuids at the given index.
     */
    public String getMessageUuids(int index) {
      return messageUuids_.get(index);
    }
    /**
     * <code>repeated string messageUuids = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the messageUuids at the given index.
     */
    public com.google.protobuf.ByteString
        getMessageUuidsBytes(int index) {
      return messageUuids_.getByteString(index);
    }
    /**
     * <code>repeated string messageUuids = 1;</code>
     * @param index The index to set the value at.
     * @param value The messageUuids to set.
     * @return This builder for chaining.
     */
    public Builder setMessageUuids(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMessageUuidsIsMutable();
      messageUuids_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string messageUuids = 1;</code>
     * @param value The messageUuids to add.
     * @return This builder for chaining.
     */
    public Builder addMessageUuids(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMessageUuidsIsMutable();
      messageUuids_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string messageUuids = 1;</code>
     * @param values The messageUuids to add.
     * @return This builder for chaining.
     */
    public Builder addAllMessageUuids(
        Iterable<String> values) {
      ensureMessageUuidsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, messageUuids_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string messageUuids = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageUuids() {
      messageUuids_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string messageUuids = 1;</code>
     * @param value The bytes of the messageUuids to add.
     * @return This builder for chaining.
     */
    public Builder addMessageUuidsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureMessageUuidsIsMutable();
      messageUuids_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Filter)
  }

  // @@protoc_insertion_point(class_scope:Filter)
  private static final net.maritimeconnectivity.mmtp.Filter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.Filter();
  }

  public static net.maritimeconnectivity.mmtp.Filter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Filter>
      PARSER = new com.google.protobuf.AbstractParser<Filter>() {
    @Override
    public Filter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Filter> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Filter> getParserForType() {
    return PARSER;
  }

  @Override
  public net.maritimeconnectivity.mmtp.Filter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

