// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmtp.proto

// Protobuf Java Version: 3.25.2
package mmtp;

public interface ReceiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Receive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Filter filter = 1;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>optional .Filter filter = 1;</code>
   * @return The filter.
   */
  net.maritimeconnectivity.mmtp.Filter getFilter();
  /**
   * <code>optional .Filter filter = 1;</code>
   */
  net.maritimeconnectivity.mmtp.FilterOrBuilder getFilterOrBuilder();
}
