// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmtp.proto

// Protobuf Java Version: 3.25.2
package mmtp;

/**
 * Protobuf type {@code Subscribe}
 */
public final class Subscribe extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Subscribe)
    SubscribeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Subscribe.newBuilder() to construct.
  private Subscribe(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Subscribe() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Subscribe();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Subscribe_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Subscribe_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.Subscribe.class, net.maritimeconnectivity.mmtp.Subscribe.Builder.class);
  }

  private int subjectOrDirectMessagesCase_ = 0;
  @SuppressWarnings("serial")
  private Object subjectOrDirectMessages_;
  public enum SubjectOrDirectMessagesCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SUBJECT(1),
    DIRECTMESSAGES(2),
    SUBJECTORDIRECTMESSAGES_NOT_SET(0);
    private final int value;
    private SubjectOrDirectMessagesCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SubjectOrDirectMessagesCase valueOf(int value) {
      return forNumber(value);
    }

    public static SubjectOrDirectMessagesCase forNumber(int value) {
      switch (value) {
        case 1: return SUBJECT;
        case 2: return DIRECTMESSAGES;
        case 0: return SUBJECTORDIRECTMESSAGES_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SubjectOrDirectMessagesCase
  getSubjectOrDirectMessagesCase() {
    return SubjectOrDirectMessagesCase.forNumber(
        subjectOrDirectMessagesCase_);
  }

  public static final int SUBJECT_FIELD_NUMBER = 1;
  /**
   * <code>string subject = 1;</code>
   * @return Whether the subject field is set.
   */
  public boolean hasSubject() {
    return subjectOrDirectMessagesCase_ == 1;
  }
  /**
   * <code>string subject = 1;</code>
   * @return The subject.
   */
  public String getSubject() {
    Object ref = "";
    if (subjectOrDirectMessagesCase_ == 1) {
      ref = subjectOrDirectMessages_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (subjectOrDirectMessagesCase_ == 1) {
        subjectOrDirectMessages_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string subject = 1;</code>
   * @return The bytes for subject.
   */
  public com.google.protobuf.ByteString
      getSubjectBytes() {
    Object ref = "";
    if (subjectOrDirectMessagesCase_ == 1) {
      ref = subjectOrDirectMessages_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (subjectOrDirectMessagesCase_ == 1) {
        subjectOrDirectMessages_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTMESSAGES_FIELD_NUMBER = 2;
  /**
   * <code>bool directMessages = 2;</code>
   * @return Whether the directMessages field is set.
   */
  @Override
  public boolean hasDirectMessages() {
    return subjectOrDirectMessagesCase_ == 2;
  }
  /**
   * <code>bool directMessages = 2;</code>
   * @return The directMessages.
   */
  @Override
  public boolean getDirectMessages() {
    if (subjectOrDirectMessagesCase_ == 2) {
      return (Boolean) subjectOrDirectMessages_;
    }
    return false;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (subjectOrDirectMessagesCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subjectOrDirectMessages_);
    }
    if (subjectOrDirectMessagesCase_ == 2) {
      output.writeBool(
          2, (boolean)((Boolean) subjectOrDirectMessages_));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (subjectOrDirectMessagesCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subjectOrDirectMessages_);
    }
    if (subjectOrDirectMessagesCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            2, (boolean)((Boolean) subjectOrDirectMessages_));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.Subscribe)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.Subscribe other = (net.maritimeconnectivity.mmtp.Subscribe) obj;

    if (!getSubjectOrDirectMessagesCase().equals(other.getSubjectOrDirectMessagesCase())) return false;
    switch (subjectOrDirectMessagesCase_) {
      case 1:
        if (!getSubject()
            .equals(other.getSubject())) return false;
        break;
      case 2:
        if (getDirectMessages()
            != other.getDirectMessages()) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (subjectOrDirectMessagesCase_) {
      case 1:
        hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getSubject().hashCode();
        break;
      case 2:
        hash = (37 * hash) + DIRECTMESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDirectMessages());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.Subscribe parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.Subscribe parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Subscribe parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.Subscribe prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Subscribe}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Subscribe)
      net.maritimeconnectivity.mmtp.SubscribeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Subscribe_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Subscribe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.Subscribe.class, net.maritimeconnectivity.mmtp.Subscribe.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.Subscribe.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      subjectOrDirectMessagesCase_ = 0;
      subjectOrDirectMessages_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Subscribe_descriptor;
    }

    @Override
    public net.maritimeconnectivity.mmtp.Subscribe getDefaultInstanceForType() {
      return net.maritimeconnectivity.mmtp.Subscribe.getDefaultInstance();
    }

    @Override
    public net.maritimeconnectivity.mmtp.Subscribe build() {
      net.maritimeconnectivity.mmtp.Subscribe result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public net.maritimeconnectivity.mmtp.Subscribe buildPartial() {
      net.maritimeconnectivity.mmtp.Subscribe result = new net.maritimeconnectivity.mmtp.Subscribe(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.Subscribe result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(net.maritimeconnectivity.mmtp.Subscribe result) {
      result.subjectOrDirectMessagesCase_ = subjectOrDirectMessagesCase_;
      result.subjectOrDirectMessages_ = this.subjectOrDirectMessages_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.Subscribe) {
        return mergeFrom((net.maritimeconnectivity.mmtp.Subscribe)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.Subscribe other) {
      if (other == net.maritimeconnectivity.mmtp.Subscribe.getDefaultInstance()) return this;
      switch (other.getSubjectOrDirectMessagesCase()) {
        case SUBJECT: {
          subjectOrDirectMessagesCase_ = 1;
          subjectOrDirectMessages_ = other.subjectOrDirectMessages_;
          onChanged();
          break;
        }
        case DIRECTMESSAGES: {
          setDirectMessages(other.getDirectMessages());
          break;
        }
        case SUBJECTORDIRECTMESSAGES_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              subjectOrDirectMessagesCase_ = 1;
              subjectOrDirectMessages_ = s;
              break;
            } // case 10
            case 16: {
              subjectOrDirectMessages_ = input.readBool();
              subjectOrDirectMessagesCase_ = 2;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int subjectOrDirectMessagesCase_ = 0;
    private Object subjectOrDirectMessages_;
    public SubjectOrDirectMessagesCase
        getSubjectOrDirectMessagesCase() {
      return SubjectOrDirectMessagesCase.forNumber(
          subjectOrDirectMessagesCase_);
    }

    public Builder clearSubjectOrDirectMessages() {
      subjectOrDirectMessagesCase_ = 0;
      subjectOrDirectMessages_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>string subject = 1;</code>
     * @return Whether the subject field is set.
     */
    @Override
    public boolean hasSubject() {
      return subjectOrDirectMessagesCase_ == 1;
    }
    /**
     * <code>string subject = 1;</code>
     * @return The subject.
     */
    @Override
    public String getSubject() {
      Object ref = "";
      if (subjectOrDirectMessagesCase_ == 1) {
        ref = subjectOrDirectMessages_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (subjectOrDirectMessagesCase_ == 1) {
          subjectOrDirectMessages_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string subject = 1;</code>
     * @return The bytes for subject.
     */
    @Override
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      Object ref = "";
      if (subjectOrDirectMessagesCase_ == 1) {
        ref = subjectOrDirectMessages_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (subjectOrDirectMessagesCase_ == 1) {
          subjectOrDirectMessages_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subject = 1;</code>
     * @param value The subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubject(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      subjectOrDirectMessagesCase_ = 1;
      subjectOrDirectMessages_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subject = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubject() {
      if (subjectOrDirectMessagesCase_ == 1) {
        subjectOrDirectMessagesCase_ = 0;
        subjectOrDirectMessages_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string subject = 1;</code>
     * @param value The bytes for subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subjectOrDirectMessagesCase_ = 1;
      subjectOrDirectMessages_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>bool directMessages = 2;</code>
     * @return Whether the directMessages field is set.
     */
    public boolean hasDirectMessages() {
      return subjectOrDirectMessagesCase_ == 2;
    }
    /**
     * <code>bool directMessages = 2;</code>
     * @return The directMessages.
     */
    public boolean getDirectMessages() {
      if (subjectOrDirectMessagesCase_ == 2) {
        return (Boolean) subjectOrDirectMessages_;
      }
      return false;
    }
    /**
     * <code>bool directMessages = 2;</code>
     * @param value The directMessages to set.
     * @return This builder for chaining.
     */
    public Builder setDirectMessages(boolean value) {

      subjectOrDirectMessagesCase_ = 2;
      subjectOrDirectMessages_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool directMessages = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirectMessages() {
      if (subjectOrDirectMessagesCase_ == 2) {
        subjectOrDirectMessagesCase_ = 0;
        subjectOrDirectMessages_ = null;
        onChanged();
      }
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Subscribe)
  }

  // @@protoc_insertion_point(class_scope:Subscribe)
  private static final net.maritimeconnectivity.mmtp.Subscribe DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.Subscribe();
  }

  public static net.maritimeconnectivity.mmtp.Subscribe getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Subscribe>
      PARSER = new com.google.protobuf.AbstractParser<Subscribe>() {
    @Override
    public Subscribe parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Subscribe> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Subscribe> getParserForType() {
    return PARSER;
  }

  @Override
  public net.maritimeconnectivity.mmtp.Subscribe getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

