/*
 * Copyright 2025 Digital Maritime Consultancy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.28.2

package net.maritimeconnectivity.mmtp;

public interface ApplicationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ApplicationMessageHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.ApplicationMessageHeader header = 1;</code>
   * @return The header.
   */
  net.maritimeconnectivity.mmtp.ApplicationMessageHeader getHeader();
  /**
   * <code>.ApplicationMessageHeader header = 1;</code>
   */
  net.maritimeconnectivity.mmtp.ApplicationMessageHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>bytes body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();

  /**
   * <code>bytes signature = 3;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
