/*
 * Copyright 2025 Digital Maritime Consultancy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.28.2

package net.maritimeconnectivity.mmtp;

public interface ApplicationMessageHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationMessageHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subject = 1;</code>
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   * <code>string subject = 1;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 1;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>.Recipients recipients = 2;</code>
   * @return Whether the recipients field is set.
   */
  boolean hasRecipients();
  /**
   * <code>.Recipients recipients = 2;</code>
   * @return The recipients.
   */
  net.maritimeconnectivity.mmtp.Recipients getRecipients();
  /**
   * <code>.Recipients recipients = 2;</code>
   */
  net.maritimeconnectivity.mmtp.RecipientsOrBuilder getRecipientsOrBuilder();

  /**
   * <code>int64 expires = 3;</code>
   * @return The expires.
   */
  long getExpires();

  /**
   * <code>string sender = 4;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 4;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>optional string qosProfile = 5;</code>
   * @return Whether the qosProfile field is set.
   */
  boolean hasQosProfile();
  /**
   * <code>optional string qosProfile = 5;</code>
   * @return The qosProfile.
   */
  java.lang.String getQosProfile();
  /**
   * <code>optional string qosProfile = 5;</code>
   * @return The bytes for qosProfile.
   */
  com.google.protobuf.ByteString
      getQosProfileBytes();

  /**
   * <code>uint32 bodySizeNumBytes = 6;</code>
   * @return The bodySizeNumBytes.
   */
  int getBodySizeNumBytes();

  net.maritimeconnectivity.mmtp.ApplicationMessageHeader.SubjectOrRecipientCase getSubjectOrRecipientCase();
}
