// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmtp.proto

// Protobuf Java Version: 3.25.2
package net.maritimeconnectivity.mmtp;

public interface ApplicationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ApplicationMessageHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.ApplicationMessageHeader header = 1;</code>
   * @return The header.
   */
  net.maritimeconnectivity.mmtp.ApplicationMessageHeader getHeader();
  /**
   * <code>.ApplicationMessageHeader header = 1;</code>
   */
  net.maritimeconnectivity.mmtp.ApplicationMessageHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>bytes body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();

  /**
   * <code>string signature = 3;</code>
   * @return The signature.
   */
  String getSignature();
  /**
   * <code>string signature = 3;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();
}
