// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmtp.proto

// Protobuf Java Version: 3.25.2
package net.maritimeconnectivity.mmtp;

public interface ConnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Connect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ownMrn = 1;</code>
   * @return Whether the ownMrn field is set.
   */
  boolean hasOwnMrn();
  /**
   * <code>optional string ownMrn = 1;</code>
   * @return The ownMrn.
   */
  String getOwnMrn();
  /**
   * <code>optional string ownMrn = 1;</code>
   * @return The bytes for ownMrn.
   */
  com.google.protobuf.ByteString
      getOwnMrnBytes();

  /**
   * <code>optional string reconnectToken = 2;</code>
   * @return Whether the reconnectToken field is set.
   */
  boolean hasReconnectToken();
  /**
   * <code>optional string reconnectToken = 2;</code>
   * @return The reconnectToken.
   */
  String getReconnectToken();
  /**
   * <code>optional string reconnectToken = 2;</code>
   * @return The bytes for reconnectToken.
   */
  com.google.protobuf.ByteString
      getReconnectTokenBytes();
}
