/*
 * Copyright 2025 Digital Maritime Consultancy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.28.2

package net.maritimeconnectivity.mmtp;

public interface ConnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Connect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ownMrn = 1;</code>
   * @return Whether the ownMrn field is set.
   */
  boolean hasOwnMrn();
  /**
   * <code>optional string ownMrn = 1;</code>
   * @return The ownMrn.
   */
  java.lang.String getOwnMrn();
  /**
   * <code>optional string ownMrn = 1;</code>
   * @return The bytes for ownMrn.
   */
  com.google.protobuf.ByteString
      getOwnMrnBytes();

  /**
   * <code>optional string reconnectToken = 2;</code>
   * @return Whether the reconnectToken field is set.
   */
  boolean hasReconnectToken();
  /**
   * <code>optional string reconnectToken = 2;</code>
   * @return The reconnectToken.
   */
  java.lang.String getReconnectToken();
  /**
   * <code>optional string reconnectToken = 2;</code>
   * @return The bytes for reconnectToken.
   */
  com.google.protobuf.ByteString
      getReconnectTokenBytes();
}
