// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmtp.proto

// Protobuf Java Version: 3.25.2
package net.maritimeconnectivity.mmtp;

public interface FetchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Fetch)
    com.google.protobuf.MessageOrBuilder {
}
