/*
 * Copyright 2025 Digital Maritime Consultancy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.28.2

package net.maritimeconnectivity.mmtp;

public interface FilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Filter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string messageUuids = 1;</code>
   * @return A list containing the messageUuids.
   */
  java.util.List<java.lang.String>
      getMessageUuidsList();
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @return The count of messageUuids.
   */
  int getMessageUuidsCount();
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @param index The index of the element to return.
   * @return The messageUuids at the given index.
   */
  java.lang.String getMessageUuids(int index);
  /**
   * <code>repeated string messageUuids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the messageUuids at the given index.
   */
  com.google.protobuf.ByteString
      getMessageUuidsBytes(int index);
}
