/*
 * Copyright 2025 Digital Maritime Consultancy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.28.2

package net.maritimeconnectivity.mmtp;

public interface MmtpMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MmtpMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MsgType msgType = 1;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  int getMsgTypeValue();
  /**
   * <code>.MsgType msgType = 1;</code>
   * @return The msgType.
   */
  net.maritimeconnectivity.mmtp.MsgType getMsgType();

  /**
   * <code>string uuid = 2;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>.ProtocolMessage protocolMessage = 3;</code>
   * @return Whether the protocolMessage field is set.
   */
  boolean hasProtocolMessage();
  /**
   * <code>.ProtocolMessage protocolMessage = 3;</code>
   * @return The protocolMessage.
   */
  net.maritimeconnectivity.mmtp.ProtocolMessage getProtocolMessage();
  /**
   * <code>.ProtocolMessage protocolMessage = 3;</code>
   */
  net.maritimeconnectivity.mmtp.ProtocolMessageOrBuilder getProtocolMessageOrBuilder();

  /**
   * <code>.ResponseMessage responseMessage = 4;</code>
   * @return Whether the responseMessage field is set.
   */
  boolean hasResponseMessage();
  /**
   * <code>.ResponseMessage responseMessage = 4;</code>
   * @return The responseMessage.
   */
  net.maritimeconnectivity.mmtp.ResponseMessage getResponseMessage();
  /**
   * <code>.ResponseMessage responseMessage = 4;</code>
   */
  net.maritimeconnectivity.mmtp.ResponseMessageOrBuilder getResponseMessageOrBuilder();

  net.maritimeconnectivity.mmtp.MmtpMessage.BodyCase getBodyCase();
}
