/*
 * Copyright 2025 Digital Maritime Consultancy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mmtp.proto
// Protobuf Java Version: 4.28.2

package net.maritimeconnectivity.mmtp;

public interface ReceiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Receive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Filter filter = 1;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>optional .Filter filter = 1;</code>
   * @return The filter.
   */
  net.maritimeconnectivity.mmtp.Filter getFilter();
  /**
   * <code>optional .Filter filter = 1;</code>
   */
  net.maritimeconnectivity.mmtp.FilterOrBuilder getFilterOrBuilder();
}
