// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmtp.proto

// Protobuf Java Version: 3.25.2
package net.maritimeconnectivity.mmtp;

/**
 * Protobuf type {@code Send}
 */
public final class Send extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Send)
    SendOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Send.newBuilder() to construct.
  private Send(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Send() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Send();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Send_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Send_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.maritimeconnectivity.mmtp.Send.class, net.maritimeconnectivity.mmtp.Send.Builder.class);
  }

  private int bitField0_;
  public static final int APPLICATIONMESSAGE_FIELD_NUMBER = 1;
  private net.maritimeconnectivity.mmtp.ApplicationMessage applicationMessage_;
  /**
   * <code>.ApplicationMessage applicationMessage = 1;</code>
   * @return Whether the applicationMessage field is set.
   */
  @Override
  public boolean hasApplicationMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.ApplicationMessage applicationMessage = 1;</code>
   * @return The applicationMessage.
   */
  @Override
  public net.maritimeconnectivity.mmtp.ApplicationMessage getApplicationMessage() {
    return applicationMessage_ == null ? net.maritimeconnectivity.mmtp.ApplicationMessage.getDefaultInstance() : applicationMessage_;
  }
  /**
   * <code>.ApplicationMessage applicationMessage = 1;</code>
   */
  @Override
  public net.maritimeconnectivity.mmtp.ApplicationMessageOrBuilder getApplicationMessageOrBuilder() {
    return applicationMessage_ == null ? net.maritimeconnectivity.mmtp.ApplicationMessage.getDefaultInstance() : applicationMessage_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getApplicationMessage());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getApplicationMessage());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.maritimeconnectivity.mmtp.Send)) {
      return super.equals(obj);
    }
    net.maritimeconnectivity.mmtp.Send other = (net.maritimeconnectivity.mmtp.Send) obj;

    if (hasApplicationMessage() != other.hasApplicationMessage()) return false;
    if (hasApplicationMessage()) {
      if (!getApplicationMessage()
          .equals(other.getApplicationMessage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasApplicationMessage()) {
      hash = (37 * hash) + APPLICATIONMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getApplicationMessage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.maritimeconnectivity.mmtp.Send parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Send parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Send parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Send parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Send parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.maritimeconnectivity.mmtp.Send parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Send parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Send parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.maritimeconnectivity.mmtp.Send parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.maritimeconnectivity.mmtp.Send parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.maritimeconnectivity.mmtp.Send parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.maritimeconnectivity.mmtp.Send parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.maritimeconnectivity.mmtp.Send prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Send}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Send)
      net.maritimeconnectivity.mmtp.SendOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Send_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Send_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.maritimeconnectivity.mmtp.Send.class, net.maritimeconnectivity.mmtp.Send.Builder.class);
    }

    // Construct using net.maritimeconnectivity.mmtp.Send.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getApplicationMessageFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      applicationMessage_ = null;
      if (applicationMessageBuilder_ != null) {
        applicationMessageBuilder_.dispose();
        applicationMessageBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.maritimeconnectivity.mmtp.Mmtp.internal_static_Send_descriptor;
    }

    @Override
    public net.maritimeconnectivity.mmtp.Send getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public net.maritimeconnectivity.mmtp.Send build() {
      net.maritimeconnectivity.mmtp.Send result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public net.maritimeconnectivity.mmtp.Send buildPartial() {
      net.maritimeconnectivity.mmtp.Send result = new net.maritimeconnectivity.mmtp.Send(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.maritimeconnectivity.mmtp.Send result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.applicationMessage_ = applicationMessageBuilder_ == null
            ? applicationMessage_
            : applicationMessageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.maritimeconnectivity.mmtp.Send) {
        return mergeFrom((net.maritimeconnectivity.mmtp.Send)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.maritimeconnectivity.mmtp.Send other) {
      if (other == getDefaultInstance()) return this;
      if (other.hasApplicationMessage()) {
        mergeApplicationMessage(other.getApplicationMessage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getApplicationMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private net.maritimeconnectivity.mmtp.ApplicationMessage applicationMessage_;
    private com.google.protobuf.SingleFieldBuilderV3<
        net.maritimeconnectivity.mmtp.ApplicationMessage, net.maritimeconnectivity.mmtp.ApplicationMessage.Builder, net.maritimeconnectivity.mmtp.ApplicationMessageOrBuilder> applicationMessageBuilder_;
    /**
     * <code>.ApplicationMessage applicationMessage = 1;</code>
     * @return Whether the applicationMessage field is set.
     */
    public boolean hasApplicationMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ApplicationMessage applicationMessage = 1;</code>
     * @return The applicationMessage.
     */
    public net.maritimeconnectivity.mmtp.ApplicationMessage getApplicationMessage() {
      if (applicationMessageBuilder_ == null) {
        return applicationMessage_ == null ? net.maritimeconnectivity.mmtp.ApplicationMessage.getDefaultInstance() : applicationMessage_;
      } else {
        return applicationMessageBuilder_.getMessage();
      }
    }
    /**
     * <code>.ApplicationMessage applicationMessage = 1;</code>
     */
    public Builder setApplicationMessage(net.maritimeconnectivity.mmtp.ApplicationMessage value) {
      if (applicationMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        applicationMessage_ = value;
      } else {
        applicationMessageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ApplicationMessage applicationMessage = 1;</code>
     */
    public Builder setApplicationMessage(
        net.maritimeconnectivity.mmtp.ApplicationMessage.Builder builderForValue) {
      if (applicationMessageBuilder_ == null) {
        applicationMessage_ = builderForValue.build();
      } else {
        applicationMessageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ApplicationMessage applicationMessage = 1;</code>
     */
    public Builder mergeApplicationMessage(net.maritimeconnectivity.mmtp.ApplicationMessage value) {
      if (applicationMessageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          applicationMessage_ != null &&
          applicationMessage_ != net.maritimeconnectivity.mmtp.ApplicationMessage.getDefaultInstance()) {
          getApplicationMessageBuilder().mergeFrom(value);
        } else {
          applicationMessage_ = value;
        }
      } else {
        applicationMessageBuilder_.mergeFrom(value);
      }
      if (applicationMessage_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ApplicationMessage applicationMessage = 1;</code>
     */
    public Builder clearApplicationMessage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      applicationMessage_ = null;
      if (applicationMessageBuilder_ != null) {
        applicationMessageBuilder_.dispose();
        applicationMessageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ApplicationMessage applicationMessage = 1;</code>
     */
    public net.maritimeconnectivity.mmtp.ApplicationMessage.Builder getApplicationMessageBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getApplicationMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.ApplicationMessage applicationMessage = 1;</code>
     */
    public net.maritimeconnectivity.mmtp.ApplicationMessageOrBuilder getApplicationMessageOrBuilder() {
      if (applicationMessageBuilder_ != null) {
        return applicationMessageBuilder_.getMessageOrBuilder();
      } else {
        return applicationMessage_ == null ?
            net.maritimeconnectivity.mmtp.ApplicationMessage.getDefaultInstance() : applicationMessage_;
      }
    }
    /**
     * <code>.ApplicationMessage applicationMessage = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.maritimeconnectivity.mmtp.ApplicationMessage, net.maritimeconnectivity.mmtp.ApplicationMessage.Builder, net.maritimeconnectivity.mmtp.ApplicationMessageOrBuilder> 
        getApplicationMessageFieldBuilder() {
      if (applicationMessageBuilder_ == null) {
        applicationMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.maritimeconnectivity.mmtp.ApplicationMessage, net.maritimeconnectivity.mmtp.ApplicationMessage.Builder, net.maritimeconnectivity.mmtp.ApplicationMessageOrBuilder>(
                getApplicationMessage(),
                getParentForChildren(),
                isClean());
        applicationMessage_ = null;
      }
      return applicationMessageBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Send)
  }

  // @@protoc_insertion_point(class_scope:Send)
  private static final net.maritimeconnectivity.mmtp.Send DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.maritimeconnectivity.mmtp.Send();
  }

  public static net.maritimeconnectivity.mmtp.Send getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Send>
      PARSER = new com.google.protobuf.AbstractParser<Send>() {
    @Override
    public Send parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Send> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Send> getParserForType() {
    return PARSER;
  }

  @Override
  public net.maritimeconnectivity.mmtp.Send getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

