CREATE TABLE subscriptions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    service_mrn       VARCHAR(255) UNIQUE                     NOT NULL,
    service_url       VARCHAR(255)                            NOT NULL,
    container_type    SMALLINT,
    data_product_type SMALLINT,
    data_reference    VARCHAR(255),
    subscription_id   UUID,
    mms_subject       VARCHAR(255),
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);
